### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by Christian-MK** [orcfax/glossary#33]
preferred label: Oracle
definition: An information management system which gathers, organizes, and stores data in order to provide access to users when required.
narrower term: Blockchain oracle

**Comment by ross-spencer** [comment]
I have a connected proposal here: https://github.com/orcfax/glossary/issues/22

> An information management system...

I like this but is there any more background to support it? https://github.com/orcfax/glossary/issues/34 is an Oracle, but in it's own right is an Oracle an information management system? Is the definition you have here more what Orcfax is defining as an Oracle and maybe worth contextualizing?

Probably not like this but to be clear what I am saying, one definition might look like:

_"In the context of the oracle problem, Orcfax as determined that an Oracle must be defined as an information management system that orders and contextualizes information that has been placed on-chain in the function of being a block-chain oracle so that historical decisions can be audited and analyzed for their veracity."_

(nb. avoiding some of our marketing terms like trust but verify)

Can this be something discussed in the Oracle WG?

In contrast to being an information management system, a bad Oracle would just put values on-chain from the outside world without any way of third-party verification. Anyone can do that in a UTxO and probably have in the past, and it's still an Oracle but it's because we're at the intersection of the trustless decentralized web and archives and records management that we want to nuance this... 

(a bit rambly today, but does any of that track?)

**Comment by Christian-MK** [comment]
narrower term: price oracle

e.g. providing the price of ada-usd on-chain, versus, a measurement of the relative humidity of a storage facility at given intervals.

**Comment by Christian-MK** [comment]
Good points @ross-spencer I think the addition of a narrower term as illustrated above might work towards drawing out thew orcfax specific nuance. What do you think of the following as a broad term def?

```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:oracle
    skos:prefLabel "oracle"@en;
    skos:definition '''
      Software which gathers data from external sources in order
      to provide access to users when required.
    ''' ;
    skos:narrower :blockchainOracle.
```

**Comment by ross-spencer** [comment]
> Software which gathers data from external sources in order to provide access to users when required.

maybe borrowing from oracle problem:

> Software that gathers data from external sources to provide access to information to blockchain users in a secure and decentralized manner

**Comment by Christian-MK** [comment]
> provide access to information to blockchain users

I was trying to draw a distinction between oracle (bt) and blockchain oracle (nt)
