### ISSUE TITLE
smart contract

### ISSUE THREAD

**Issue by peterVG** [orcfax/glossary#8]
definition: Smart contracts are software programs that execute conditional logic on next-generation blockchains like Cardano (e.g. when event X happens, trigger action Y). Because their source code is immutably stored and run on decentralized blockchain networks, they constrain the range of permissible user actions and their effects.

This means that they can reasonably be expected to have the same outcome each time they are triggered. Therefore smart contracts are often referred to as having "trustless" qualities. The term "trustless" is a popular word to characterize blockchain technology because its cryptographic proofs and distributed consensus algorithms ensure that its shared data is authentic, accurate, and secure without reliance on a trusted third-party to verify the information.

**Comment by peterVG** [comment]
DW: there really is no such thing as a "smart contract" on Cardano. The one well-defined entity that we do have is a Plutus script. Tx-builder code is also sufficiently well defined - at least the output of it is a serialized tx that gets submitted to chain. The collection of code that makes a smart contract, "smart" ... is vague. "Smart" from IoT land means "does stuff without your input" which is intentionally not how cardano works. 

So asking "how do I deploy my dapp?" doesn't actually apply to Cardano.

**Comment by ross-spencer** [comment]
> So asking "how do I deploy my dapp?" doesn't actually apply to Cardano.

I _think_ I understand the spirit of this but I'm not sure it's helpful in the glossary (also note OpShin and Aiken use deploy to mean 'deploy a script so that it is accessible to the ledger'). But deploying a dApp is likely to involve (with still growing understanding):

* having some smart contract that is deployed on-chain.
* building transactions (referencing a smart contract and other inputs)
* having off-chain monitoring, e.g. for events (currency-pair changes), 
* other miscellaneous off-chain pieces that do something that ultimately end in a transaction.

Which is more like a traditional view of deployment and implies a certain pattern for deployment on Cardano. But yes, the Cardano smart contract isn't some singular application or compute resource that does something for us. 

I wonder too if the trustless aspect can be characterized as a third-party end-user can claim something from a provider without human intervention? (if the inputs to their transaction satisfy the properties of some function?)
