### ISSUE TITLE
script

### ISSUE THREAD

**Issue by peterVG** [orcfax/glossary#9]
narrower term: Plutus script

**Comment by ross-spencer** [comment]
broader term: computer application?

"script" for me conjures a bash or shell script that performs a specific task when it is run. (the complexity can be arbitrary)

**Comment by Christian-MK** [comment]
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:plutusScript
    skos:prefLabel "Plutus script"@en;
    skos:definition '''
      A piece of code written in the Plutus Core programming
      language which is used to create smart contracts for the
      Cardano blockchain.
    ''' ;
    skos:broader :script.
```

**Comment by waalge** [comment]
I think our glossary should stay focused on our domain 

Adding fields: 

> skos:broader :computerApplication
> skos:narrower :script.

Doesn't really aid us. We don't need to maintain our own definition of "computer application". That is until the day we start using the term to mean something specific or in away that might be distinct from "common understanding" 

We can use TTL to reference another domain. Here `:` is shorthand for the orcfax domain (that's what the first line of each file says). I don't know a domain to use, but i'm sure there is one out there. Does w3 have their own one?

Additional notes: 

1. script is not narrow than plutus script. It is generally more general/ just different. Loosely a script is a single file program that is interpreted rather than compiled. In reality these lines are blurred (a single file could iimport a bunch of other files, the interpreter might do things that look very much like a compiler , etc) 

2. In cardano, "validator" is a (near) synonym for "plutus script", but for us that term refers to a role in the orcfax network. So we use "plutus script" and when the context is sufficiently clear, simply "script"

**Comment by Christian-MK** [comment]
> 1. script is not narrow than plutus script. It is generally more general/ just different.

fixed

**Comment by waalge** [comment]
We are not going to write our own definition of `script` _ie_ `:script` isn't going to exists. 

> written in the Plutus Core programming language

It isnt. Plutus Core is typed. What you're referring to is UPLC. Moreover, no-one is actually _writing_ in these languages. You write in another language, eg aiken, and compile targetting uplc. 
 
 > which is used to create smart contracts for the Cardano blockchain.
 
 I don't know what a smart contract for the cardano blockchain is. Its vocab borrowed from eth where the design is quite different. People use it in cardano vaguely without specifying which bits they're actually referring to. 
 
 What is important here? 
 
 It is code executed by cardano nodes when accepting txs. 
 A script can govern the spending from its payment address, 
 the minting (and burning) of its own tokens,
 as well as withdraws, certificates and more with conway/chang. 
 A tx will be rejected from the ledger if the script errors. 
 The hash (blake2b_256) is the policy if of its tokens and determines the payment credentials of the spending address and stake credential of the withdrawal address _etc_.

**Comment by Christian-MK** [comment]
@waalge please propose a definition
